name: "Build kernels"

env:
  OUT_DIR: "${{ github.workspace }}/out"
  KERNEL_SU_NEXT_BRANCH: "next-susfs"
  SUSFS_BRANCH: "kernel-4.9"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    name: "Parse repos.json and Set Build Date"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.matrix.outputs.repos }}
      builddate: ${{ steps.builddate.outputs.builddate }}
    steps:
      - uses: actions/checkout@v3

      - id: matrix
        name: "Generate Matrix from repos.json"
        run: |
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          jq -s '[.[][]]' repos/repos*.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - id: builddate
        name: "Set Build Date"
        run: echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "Build kernel - ${{ matrix.repos.kernelSource.name }}"
    runs-on: ubuntu-latest
    needs: [Set-repos]
    strategy:
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
      max-parallel: 4
      fail-fast: false
    env:
      WORKSPACE: ${{ github.workspace }}
      BUILDDATE: "${{ needs.Set-repos.outputs.builddate }}"
      KERNEL_NAME: ${{ matrix.repos.kernelSource.name }}
      KERNEL_REPO: ${{ matrix.repos.kernelSource.repo }}
      KERNEL_BRANCH: ${{ matrix.repos.kernelSource.branch }}
      KERNEL_DEVICE: ${{ matrix.repos.kernelSource.device }}
      DEFCONFIG_NAME: ${{ matrix.repos.kernelSource.defconfig }}
      WITH_KERNELSU: ${{ matrix.repos.withKernelSU }}
      CCACHE_ENABLED: ${{ matrix.repos.ccache }}
      USE_ANYKERNEL: ${{ matrix.repos.AnyKernel3.use }}
      RELEASE_ENABLED: ${{ matrix.repos.AnyKernel3.release }}
      ANYKERNEL_PARAMS: ${{ toJSON(matrix.repos.AnyKernel3) }}
    steps:
      - name: "Install Prerequisites"
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libssl-dev libfl-dev curl git ftp lftp wget libarchive-tools \
            ccache python3 python3-dev zip unzip tar gzip bzip2 rar unrar

      - name: "Create ccache Key"
        if: ${{ env.CCACHE_ENABLED == 'true' }}
        id: ccache_key
        run: |
          ccache -o compression=false -o cache_dir=$HOME/.ccache
          echo "CACHE_KEY=$(echo -n '${{ toJSON(matrix.repos) }}' | base64 -w 0 | cut -c -48)" >> $GITHUB_OUTPUT

      - name: "Cache ccache Files"
        if: ${{ env.CCACHE_ENABLED == 'true' }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.ccache
            ${{ env.OUT_DIR }}
          key: ccache-${{ env.KERNEL_NAME }}-${{ steps.ccache_key.outputs.CACHE_KEY }}-${{ env.BUILDDATE }}

      - name: "Setup AnyKernel3"
        run: |
          set -e # Exit immediately if a command fails

          ANYKERNEL_REPO=$(jq -r ".repo" <<< "$ANYKERNEL_PARAMS")
          ANYKERNEL_BRANCH=$(jq -r ".branch" <<< "$ANYKERNEL_PARAMS")
          git clone --recursive --depth=1 -j $(nproc) --branch "$ANYKERNEL_BRANCH" "$ANYKERNEL_REPO" AnyKernel3
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "${{ env.SUSFS_BRANCH }}"

      - name: "Clone Kernel Source"
        run: |
          set -e # Exit immediately if a command fails
          git clone --recursive --depth=1 -j $(nproc) --branch "$KERNEL_BRANCH" "$KERNEL_REPO" "$KERNEL_NAME"

      - name: "Get toolchains"
        env:
          toolchains: "${{ toJSON(matrix.repos.toolchains) }}"
        run: |
          set -e # Exit immediately if a command fails
          num=$(echo "$toolchains" | jq 'length')
          for i in $(seq 0 "$((num-1))"); do # Added quotes around num-1
            name=$(echo "$toolchains" | jq -r ".[$i].name")
            repo=$(echo "$toolchains" | jq -r ".[$i].repo")
            branch=$(echo "$toolchains" | jq -r ".[$i].branch")
            url=$(echo "$toolchains" | jq -r ".[$i].url")
            if [ -z "$url" ] || [ "$url" = "null" ]; then
              git clone --recursive --depth=1 -j $(nproc) --branch "$branch" "$repo" "$name" # Added quotes around variables
            else
              wget "$url"
              file="${url##*/}"
              mkdir -p "$name" # Added quotes
              case "$file" in
                *.zip)    unzip -d "$name" "$file" ;; # Added quotes
                *.tar)    tar xvf "$file" -C "$name" ;; # Added quotes
                *.tar.gz) tar zxvf "$file" -C "$name" ;; # Added quotes
                *.rar)    unrar x "$file" "$name" ;; # Added quotes
                *)        echo "unknown file type: $file" ;;
              esac
              rm "$file" # Added quotes
            fi
            jq -r ".[$i].binPath[]" <<< "$toolchains" | while read -r bp; do
              echo "$WORKSPACE/$name/$bp" >> "$GITHUB_PATH" # Added quotes
            done
          done
          echo "$WORKSPACE/$name/bin" >> "$GITHUB_PATH"  # Add bin directory to PATH and added quotes

      - name: "Set Build Arguments"
        id: generate-args
        env:
          PARAMS: "${{ toJSON(matrix.repos.params) }}"
        run: |
          set -e # Exit immediately if a command fails
          args=""
          ARCH=$(echo "$PARAMS" | jq -r ".ARCH")
          if [ -n "$ARCH" ]; then
            args="$args ARCH=$ARCH"
          fi

          CC=$(echo "$PARAMS" | jq -r ".CC")
          if [ -n "$CC" ]; then
            if [ "${CCACHE_ENABLED}" = "true" ]; then
              args="$args CC=\"ccache $CC\"" # You might not need full path here now
            else
              args="$args CC=$CC" # You might not need full path here now
            fi
          fi
          mapfile -t cmds < <(jq -r '.externalCommand | to_entries[] | "\(.key)=\(.value)"' <<< "$PARAMS")
          for cmd in "${cmds[@]}"; do
            key=${cmd%%=*}
            val=${cmd#*=}
            [[ "$val" == */* ]] && val="${WORKSPACE}/$val"
            args="$args $key=$val"
          done
          echo "args=$args" >> $GITHUB_OUTPUT
          echo "ARCH=$ARCH" >> $GITHUB_OUTPUT

      - name: "Apply SUSFS Patches"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          set -e # Exit immediately if a command fails

          git apply --check 50_add_susfs_in_kernel-4.9.patch
          if [ $? -ne 0 ]; then
            echo "::error title=SUSFS Patch Failed::Failed to apply 50_add_susfs_in_kernel-4.9.patch"
            exit 1
          fi
          patch -p1 < 50_add_susfs_in_kernel-4.9.patch

          if [ -d "KernelSU-Next" ]; then
            cd KernelSU-Next
            git apply --check 10_enable_susfs_for_ksu.patch
            if [ $? -ne 0 ]; then
              echo "::error title=KernelSU-Next SUSFS Patch Failed::Failed to apply 10_enable_susfs_for_ksu.patch"
              exit 1
            fi
            patch -p1 --forward < 10_enable_susfs_for_ksu.patch
            cd ..
          fi

      - name: "Add SUSFS Config"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          set -e # Exit immediately if a command fails
          CONFIG_FILE="arch/${{ steps.generate-args.outputs.ARCH }}/configs/${DEFCONFIG_NAME}"
          for cfg in "CONFIG_KSU=y" "CONFIG_KSU_SUSFS=y" "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" \
                     "CONFIG_KSU_SUSFS_SUS_PATH=y" "CONFIG_KSU_SUSFS_SUS_MOUNT=y" \
                     "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" \
                     "CONFIG_KSU_SUSFS_SUS_KSTAT=y" "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" \
                     "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" \
                     "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" "CONFIG_KSU_SUSFS_ENABLE_LOG=y" \
                     "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" \
                     "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" "CONFIG_KSU_SUSFS_SUS_SU=y" "CONFIG_TMPFS_XATTR=y"; do
            echo "$cfg" | sudo tee -a "$CONFIG_FILE"
          done

      - name: "Update KernelSU"
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          ARCH: ${{ steps.generate-args.outputs.ARCH }}
        if: ${{ env.WITH_KERNELSU == 'true' }}
        run: |
          set -e # Exit immediately if a command fails
          [ -d "KernelSU" ] && rm -rf "KernelSU"
          [ -d "drivers/kernelsu" ] && rm -rf "drivers/kernelsu"

          # Download and execute setup.sh - consider security implications!
          # Ideally, vendor this script and verify its checksum.
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/${{ env.KERNEL_SU_NEXT_BRANCH }}/kernel/setup.sh" -o setup.sh # Download script
          chmod +x setup.sh # Make it executable

          # Security:  Consider verifying a checksum of setup.sh here before executing.
          # Example (you'd need to pre-calculate the known good checksum):
          # KNOWN_CHECKSUM="your_known_checksum_here"
          # ACTUAL_CHECKSUM=$(sha256sum setup.sh | awk '{print $1}')
          # if [ "$ACTUAL_CHECKSUM" != "$KNOWN_CHECKSUM" ]; then
          #   echo "::error title=Checksum Verification Failed::Checksum of setup.sh does not match expected value!"
          #   exit 1
          # fi

          ./setup.sh ${{ env.KERNEL_SU_NEXT_BRANCH }} # Execute the script
          rm setup.sh #remove the script
          CONFIG_FILE="arch/${ARCH}/configs/${DEFCONFIG_NAME}"
          for cfg in "CONFIG_KPROBES=y" "CONFIG_HAVE_KPROBES=y" "CONFIG_KPROBE_EVENTS=y"; do
            echo "$cfg" | sudo tee -a "$CONFIG_FILE"
          done
          cat "$CONFIG_FILE"

      - name: "Make defconfig"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          set -e # Exit immediately if a command fails
          make "${ARGS}" "${DEFCONFIG_NAME}"  # Corrected quoting

      - name: "Build Kernel"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          set -e # Exit immediately if a command fails
          make "${ARGS}" # Still need to quote ARGS

      - name: "Prepare AnyKernel3"
        if: ${{ env.USE_ANYKERNEL == 'true' }}
        run: |
          set -e # Exit immediately if a command fails
          mkdir -p AnyKernel3/files
          cp "${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/Image" AnyKernel3/
          cp "${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/Image.gz-dtb" AnyKernel3/
          cp "${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/dtbo" AnyKernel3/
          cp "${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/dtbo.img" AnyKernel3/

      - name: "Pack AnyKernel3.zip"
        if: ${{ env.USE_ANYKERNEL == 'true' }}
        run: |
          set -e # Exit immediately if a command fails
          cd AnyKernel3/
          zip -q -r "../${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.BUILDDATE }}.zip" *

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.BUILDDATE }}"
          path: |
            ${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/Image
            ${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/Image.gz-dtb
            ${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/dtb
            ${{ env.OUT_DIR }}/arch/${{ steps.generate-args.outputs.ARCH }}/boot/dtbo.img
            ${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.BUILDDATE }}.zip
          if-no-files-found: ignore
          retention-days: 7

      - name: "Create GitHub Release"
        if: ${{ env.USE_ANYKERNEL == 'true' && env.RELEASE_ENABLED == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUILDDATE }}.${{ github.run_number }}
          files: "${{ env.WORKSPACE }}/${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ env.BUILDDATE }}.zip"
          generate_release_notes: true
          
